import pytest
import rasterio
from rasterio.crs import CRS
from rasterio.warp import transform_bounds

from usgs_topo_tiler.extent import get_extent

# yapf: disable
# Test cases are generated by a process described here:
# https://github.com/kylebarron/usgs-topo-tiler/issues/8#issuecomment-626104877
AUTOMATED_TEST_CASES = [
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/FL/FL_Fort%20Pierce_346296_1972_10000_geo.tif',
        [-80.35, 27.4166667, -80.266667, 27.5], 10000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/PR/PR_Rosario_362248_1964_20000_geo.tif',
        [-67.125, 18.125, -67.0, 18.25], 20000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Torrance_299925_1934_20000_geo.tif',
        [-118.43333329999999, 33.8, -118.3, 33.9], 20000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/PR/PR_Arecibo_362029_1964_20000_geo.tif',
        [-66.75, 18.375, -66.625, 18.5], 20000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/SC/SC_Bulls%20Island_260669_1919_21120_geo.tif',
        [-79.625, 32.875, -79.5, 33.0], 21120],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/SC/SC_Melgrove_260683_1919_21120_geo.tif',
        [-80.0, 32.875, -79.875, 33.0], 21120],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/SC/SC_The%20Jetties_260686_1919_21120_geo.tif',
        [-79.875, 32.625, -79.75, 32.75], 21120],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Big%20Maria%20Mts%20SE_288400_1955_24000_geo.tif',
        [-114.625, 33.75, -114.5, 33.875], 24000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/IL/IL_Park%20Ridge_308431_1963_24000_geo.tif',
        [-87.875, 42.0, -87.75, 42.125], 24000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MS/MS_Leland_335987_1967_24000_geo.tif',
        [-91.0, 33.375, -90.875, 33.5], 24000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MA/MA_Marblehead%20North_351077_1977_25000_geo.tif',
        [-70.875, 42.5, -70.75, 42.625], 25000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MI/MI_Cooperton_277603_1983_25000_geo.tif',
        [-84.875, 44.125, -84.75, 44.25], 25000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MA/MA_Norwood_351182_1947_25000_geo.tif',
        [-71.25, 42.125, -71.125, 42.25], 25000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/PR/PR_Bayaney_362345_1952_30000_geo.tif',
        [-66.875, 18.25, -66.75, 18.375], 30000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/PR/PR_Yauco_362605_1946_30000_geo.tif',
        [-66.875, 18.0, -66.75, 18.125], 30000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/PR/PR_Aguas%20Buenas_362323_1952_30000_geo.tif',
        [-66.125, 18.25, -66.0, 18.375], 30000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Fowlkes_108284_1919_31680_geo.tif',
        [-98.875, 33.875, -98.75, 34.0], 31680],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MA/MA_Mt%20Toby_463003_1944_31680_geo.tif',
        [-72.625, 42.375, -72.5, 42.5], 31680],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MA/MA_Ludlow_351848_1944_31680_geo.tif',
        [-72.5, 42.125, -72.375, 42.25], 31680],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Marquez%20No%204_128391_1925_48000_geo.tif',
        [-96.375, 31.0, -96.25, 31.125], 48000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Roby%202-b_128417_1926_48000_geo.tif',
        [-100.5, 32.875, -100.375, 33.0], 48000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Crowther%20No%203_123898_1925_48000_geo.tif',
        [-98.5, 28.5, -98.375, 28.625], 48000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/ME/ME_Columbia%20Falls_460327_1921_62500_geo.tif',
        [-67.75, 44.625, -67.625, 44.75], 62500],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CT/CT_Niantic_461318_1938_62500_geo.tif',
        [-72.25, 41.25, -72.125, 41.375], 62500],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/PR/PR_Barranquitas%20NO_361934_1947_10000_geo.tif',
        [-66.375, 18.1875, -66.3125, 18.25], 10000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/PR/PR_El%20Yunque%20NE_361988_1947_10000_geo.tif',
        [-65.8125, 18.3125, -65.75, 18.375], 10000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/PR/PR_Bayaney%20NO_361942_1947_10000_geo.tif',
        [-66.875, 18.3125, -66.8125, 18.375], 10000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Dallas%20(A)_109075_1968_12000_geo.tif',
        [-96.875, 32.8125, -96.8125, 32.875], 12000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/KS/KS_Leonardville_801859_1957_20000_geo.tif',
        [-97.0, 39.25, -96.75, 39.5], 20000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/KS/KS_White%20City%20South_122725_1927_20000_geo.tif',
        [-96.75, 38.75, -96.5, 39.0], 20000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/KS/KS_Randolph_801953_1957_20000_geo.tif',
        [-96.75, 39.25, -96.5, 39.5], 20000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/ME/ME_Seven%20Islands_460866_1955_24000_geo.tif',
        [-69.75, 46.75, -69.5, 47.0], 24000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/ME/ME_Brooklin_460248_1981_24000_geo.tif',
        [-68.0, 46.25, -67.75, 46.5], 24000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/PA/PA_Howard_461771_1944_24000_geo.tif',
        [-77.75, 41.0, -77.5, 41.25], 24000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/HI/HI_Island%20of%20Lanai_467936_1923_31680_geo.tif',
        [-157.08333330000002, 20.7083333, -156.79166669999998, 20.9583333],
        31680],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/UT/UT_Wasatch_252663_1922_31680_geo.tif',
        [-111.5, 39.0, -111.25, 39.25], 31680],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MN/MN_Juneberry_805494_1930_31680_geo.tif',
        [-96.5, 48.75, -96.25, 49.0], 31680],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/ME/ME_Stockholm_807692_1927_48000_geo.tif',
        [-68.25, 47.0, -68.0, 47.25], 48000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/VT/VT_Guildhall_337799_1931_48000_geo.tif',
        [-71.75, 44.5, -71.5, 44.75], 48000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/KY/KY_Lockport_804229_1906_48000_geo.tif',
        [-85.0, 38.25, -84.75, 38.5], 48000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Dilley_122265_2002_50000_geo.tif',
        [-99.25, 28.5, -99.0, 28.75], 50000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Alpine%20Butte_465291_1947_50000_geo.tif',
        [-118.0, 34.5, -117.75, 34.75], 50000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Harrison%20Bay%20D-5_463769_1962_50000_geo.tif',
        [-153.0, 70.75, -152.4, 71.0], 50000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MO/MO_Big%20Piney_324720_1954_62500_geo.tif',
        [-92.25, 37.5, -92.0, 37.75], 62500],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/VT/VT_Bennington_337855_1954_62500_geo.tif',
        [-73.25, 42.75, -73.0, 43.0], 62500],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/LA/LA_Farmerville_334528_1952_62500_geo.tif',
        [-92.5, 32.75, -92.25, 33.0], 62500],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Karluk%20D-5_356495_1951_63360_geo.tif',
        [-155.66666669999998, 57.75, -155.33333330000002, 58.0], 63360],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Bethel%20A-1_354405_1979_63360_geo.tif',
        [-159.375, 60.0, -159.0, 60.25], 63360],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Livengood%20A-2_463911_1952_63360_geo.tif',
        [-148.0, 65.0, -147.5, 65.25], 63360],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/OK/OK_Norman_802551_1893_96000_geo.tif',
        [-97.5, 35.0, -97.25, 35.25], 96000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MA/MA_Billerica_350850_1987_25000_geo.tif',
        [-71.5, 42.5, -71.25, 42.625], 25000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MA/MA_Somerset_351310_1985_25000_geo.tif',
        [-71.25, 41.75, -71.0, 41.875], 25000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MA/MA_Barre_350835_1988_25000_geo.tif',
        [-72.25, 42.375, -72.0, 42.5], 25000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MA/MA_Warwick_352419_1932_48000_geo.tif',
        [-72.5, 42.625, -72.25, 42.75], 48000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/NY/NY_Starrucca_144032_1924_48000_geo.tif',
        [-75.5, 41.875, -75.25, 42.0], 48000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MA/MA_Winchendon_352420_1932_48000_geo.tif',
        [-72.25, 42.625, -72.0, 42.75], 48000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Elizabeth%20Lake_299035_1915_96000_geo.tif',
        [-118.5, 34.5, -118.0, 35.0], 96000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Big%20Bar_299032_1909_96000_geo.tif',
        [-123.5, 40.5, -123.0, 41.0], 96000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/NM/NM_Tularosa_189434_1911_96000_geo.tif',
        [-106.5, 33.0, -106.0, 33.5], 96000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TN/TN_Statesville_155953_1942_100000_geo.tif',
        [-86.25, 35.75, -85.75, 36.25], 100000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TN/TN_Cookeville_149603_1944_100000_geo.tif',
        [-85.75, 35.75, -85.25, 36.25], 100000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TN/TN_Mc%20Minnville_150199_1943_100000_geo.tif',
        [-86.25, 35.25, -85.75, 35.75], 100000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MT/MT_Heart%20Butte_268564_1918_125000_geo.tif',
        [-113.0, 48.0, -112.5, 48.5], 125000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/GA/GA_Atlanta_467587_1890_125000_geo.tif',
        [-84.5, 33.5, -84.0, 34.0], 125000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CO/CO_Pagosa%20Springs_467127_1927_125000_geo.tif',
        [-107.5, 37.0, -107.0, 37.5], 125000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/WA/WA_Mt%20Baker_242611_1909_192000_geo.tif',
        [-122.0, 48.5, -121.5, 49.0], 192000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Big%20Bar_299708_1911_192000_geo.tif',
        [-123.5, 40.5, -123.0, 41.0], 192000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Big%20Bar%20and%20Vicinity_465343_1915_250000_geo.tif',
        [-123.75, 40.5, -123.0, 41.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Big%20Bar%20and%20Vicinity_299743_1915_250000_geo.tif',
        [-123.75, 40.5, -123.0, 41.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Big%20Bar%20and%20Vicinity_465341_1915_250000_geo.tif',
        [-123.75, 40.5, -123.0, 41.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Encino_117702_1992_100000_geo.tif',
        [-99.0, 26.5, -98.0, 27.0], 100000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/NC/NC_Henderson_162162_1991_100000_geo.tif',
        [-79.0, 36.0, -78.0, 36.5], 100000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Zapata_123672_1985_100000_geo.tif',
        [-100.0, 26.5, -99.0, 27.0], 100000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Cotulla_123888_1929_125000_geo.tif',
        [-100.0, 28.0, -99.0, 28.5], 125000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Santa%20Ana_302139_1960_250000_geo.tif',
        [-118.0, 33.0, -116.0, 34.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_San%20Luis%20Obispo_302131_1958_250000_geo.tif',
        [-122.0, 35.0, -120.0, 36.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/TX/TX_Beaumont_707218_1984_250000_geo.tif',
        [-96.0, 30.0, -94.0, 31.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Talkeetna_464161_1965_250000_geo.tif',
        [-153.0, 62.0, -150.0, 63.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Mt%20Saint%20Elias_361195_1959_250000_geo.tif',
        [-141.0, 60.0, -138.0, 61.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Beechey%20Point_360621_1960_250000_geo.tif',
        [-150.0, 70.0, -147.0, 71.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Searles%20Lake_299884_1915_250000_geo.tif',
        [-118.0, 35.0, -117.0, 36.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AZ/AZ_Kaibab_315511_1886_250000_geo.tif',
        [-113.0, 36.0, -112.0, 37.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/MT/MT_Three%20Forks_268807_1894_250000_geo.tif',
        [-112.0, 45.0, -111.0, 46.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Teller_361556_1951_250000_geo.tif',
        [-169.0, 65.0, -165.0, 66.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Teller_361550_1950_250000_geo.tif',
        [-169.0, 65.0, -165.0, 66.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/AK/AK_Wainwright_361658_1955_250000_geo.tif',
        [-163.0, 70.0, -159.0, 71.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/OR/OR_Coos%20Bay_283315_1962_250000_geo.tif',
        [-125.0, 42.0, -124.0, 44.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Santa%20Maria_302151_1962_250000_geo.tif',
        [-121.0, 33.0, -120.0, 35.0], 250000],
    [
        'https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/HistoricalTopo/GeoTIFF/CA/CA_Eureka_299766_1949_250000_geo.tif',
        [-125.0, 40.0, -124.0, 42.0], 250000]]
# yapf: enable
#


@pytest.mark.parametrize("url,map_bounds,scale", AUTOMATED_TEST_CASES)
def test_extent(url, map_bounds, scale):
    with rasterio.open(url) as r:
        # Convert image bounds to wgs84
        image_wgs_bounds = transform_bounds(
            r.crs, CRS.from_epsg(4326), *r.bounds)

        extent = get_extent(image_wgs_bounds, url)
        for x, y in zip(extent, map_bounds):
            msg = f'{extent}, {map_bounds} not approx equal'
            assert x == pytest.approx(y), msg
